#sdk: "/var/lib/gems/1.8/gems/rhodes-3.4.2"
sdkversion: 3.4.2
name: MacoTec
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  # configuration: Release
  sdk: iphonesimulator5.0
  # sdk: iphoneos6.1
  provisionprofile: 
  codesignidentity: "iPhone Developer: Oliver Schobel (TBZ9347JVY)"
  entitlements:
  BundleIdentifier: com.rhomobile.macotec
  BundleURLScheme: macotec
wp:
  productid: 'c61da3d0-477e-0130-9d74-0021cc4acfa5'
symbian:
  uid: '0xe52ea902'
android:
  version: 4.0.3
  emulator: MacoTec
  android_title: 0

extensions: ["json", "another-extension"]

capabilities:
  - camera